# Client config
server_url:
  http://192.168.3.21:9969

com_port:
  COM6

basic_options:
  --chip   esp8266
  --baud   921600
  --before default_reset
  --after  soft_reset

flash_options:
  --flash_mode dio
  --flash_freq 40m
  --flash_size 2MB

firmware_list:
    0xd000: 
        /home/cloudsir/Desktop/ESP8266_RTOS_SDK/iot_-project/build/ota_data_initial.bin

    0x0000: 
        /home/cloudsir/Desktop/ESP8266_RTOS_SDK/iot_-project/build/bootloader/bootloader.bin 

    0x10000: 
        /home/cloudsir/Desktop/ESP8266_RTOS_SDK/iot_-project/build/iot_app.bin 
        
    0x8000: 
        /home/cloudsir/Desktop/ESP8266_RTOS_SDK/iot_-project/build/partitions_two_ota.bin
